apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"        
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: vinicius/mocked-api:{{tag}}
          ports: 
          - containerPort: 3000
--- 
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000   
      nodePort: 30000   
  type: LoadBalancer

