apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocked-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocked-api
  template:
    metadata:
      labels:
        app: mocked-api
    spec:
      containers:
        - name: api
          image: registry.hub.docker.com/viniciusponte/mocked-api:latest  # Substitua 11 pela tag real se necessário
          ports:
          - containerPort: 3000
