apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocked-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocked-api
  template:
    metadata:
      labels:
        app: mocked-api
    spec:
      containers:
        - name: api
          image: registry.hub.docker.com/viniciusponte/mocked-api:latest  # Substitua 11 pela tag real se necessário
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
